### ISSUE TITLE
CI broken due to Meson

### ISSUE THREAD

**Issue by BBasile** [dlang-community/tinyendian#7]
See https://travis-ci.org/dlang-community/tinyendian

We had a similar issue a few ago with D-Yaml. Do you have some time for this @ximion ?

**Comment by ximion** [comment]
Yeah, this is issue https://github.com/mesonbuild/meson/pull/2889 , to be fixed in the next Meson release.
So, in Travis you could work around that by replacing the `pip3 install meson` line with `pip3 install 'git+git://github.com/mesonbuild/meson.git@6d7a8a0ea4f327a1f8616eeefdfc7164864ccb04` or wait a bit for Meson 0.44.1 or 0.45 to be released (which is hopefully soon, this release is taking especially long, unfortunately).

**Comment by BBasile** [comment]
Sorry i didn't  remember that you had made a PR directly to the Meson project.
We'll just wait then.

**Comment by ximion** [comment]
@BBasile Yeah, sorry for the inconvenience... Meson is usually very bug-free, but the 0.44 release was quite an exception. All the issues (except for the DMD notation) do have unit tests now, so the issues shouldn't appear again.
